ShoeStoreManagement/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoeStoreManagement.Areas.Identity.Data;
using ShoeStoreManagement.Core.Enums;
using ShoeStoreManagement.Core.Models;
using ShoeStoreManagement.Core.ViewModel;
using ShoeStoreManagement.CRUD.Interfaces;
using System.Security.Claims;
using Image = ShoeStoreManagement.Core.Models.Image;

namespace ShoeStoreManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private const int minusIndex = 35;

        private readonly ILogger<ProductController> _logger;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IProductCRUD _productCRUD;
        private readonly ICartCRUD _cartCRUD;
        private readonly ICartDetailCRUD _cartDetailCRUD;
        private readonly ISizeDetailCRUD _sizeDetailCRUD;
        private readonly IProductCategoryCRUD _productCategoryCRUD;
        private readonly IImageCRUD _imageCRUD;
        //private IList<SelectListItem>? test;

        private readonly UserManager<ApplicationUser> _usermanager;
        private static ProductVM _productVM = new ProductVM();



        public ProductController(ILogger<ProductController> logger, IProductCRUD productCRUD, UserManager<ApplicationUser> usermanager
            , IProductCategoryCRUD productCategoryCRUD, ISizeDetailCRUD sizeDetailCRUD, ICartCRUD cartCRUD, ICartDetailCRUD cartDetailCRUD, IWebHostEnvironment webHostEnvironment, IImageCRUD imageCRUD)
        {
            _logger = logger;
            _productCRUD = productCRUD;
            _productCategoryCRUD = productCategoryCRUD;
            _sizeDetailCRUD = sizeDetailCRUD;
            _cartCRUD = cartCRUD;
            _cartDetailCRUD = cartDetailCRUD;
            _imageCRUD = imageCRUD;
            _usermanager = usermanager;
            _hostEnvironment = webHostEnvironment;
            Init();
        }

        private void Init()
        {
            _productVM.productCategories = _productCategoryCRUD.GetAllAsync().Result;
            _productVM.products = _productCRUD.GetAllAsync().Result;
            for (int i = 0; i < _productVM.products.Count; i++)
            {
                _productVM.products[i].SetCategory(_productVM.productCategories);
                List<SizeDetail> sizeList = _sizeDetailCRUD.GetAllByIdAsync(_productVM.products[i].ProductId).Result;
                _productVM.products[i].Sizes = sizeList;
            }

        }

        [HttpPost]
        public IActionResult ToCart(Product product)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Cart? cart = _cartCRUD.GetAsync(userId).Result;

            if (cart == null)
            {
                cart = new Cart();
                cart.UserId = userId;
                _cartCRUD.CreateAsync(cart);
            }

            //Product product = _productCRUD.GetByIdAsync(productID).Result; 

            if (product == null)
            {
                return NotFound();
            }

            List<SizeDetail> sizes = _sizeDetailCRUD.GetAllByIdAsync(product.ProductId).Result;

            List<string> checkedSize = product.TestSize; // Store checked sizes
            List<string> checkedSizeAmount = new List<string>(); // Store amount of checked sizes

            foreach (string i in product.TestSizeAmount) // Remove null indexes
            {
                if (!string.IsNullOrEmpty(i))
                    checkedSizeAmount.Add(i);
            }

            // Handle changes in size's amount
            for (int i = 0; i < checkedSize.Count; i++)
            {
                if (checkedSizeAmount[i] == null)
                    continue;

                SizeDetail? sizeDetail = _sizeDetailCRUD.GetProductSizeAsync(product.ProductId, int.Parse(checkedSize[i])).Result;

                if (sizeDetail == null) return NotFound();

                sizeDetail.Amount -= int.Parse(checkedSizeAmount[i]);
                _sizeDetailCRUD.Update(sizeDetail);

                CartDetail? cartDetail = null;

                foreach (CartDetail cd in _cartDetailCRUD.GetAllAsync(cart.CartId).Result) // Find Cart Detail of Chosen Product with the Size we need
                {
                    if (cd.ProductId.Equals(product.ProductId) && cd.Size == sizeDetail.Size)
                        cartDetail = cd;
                }

                if (cartDetail != null)
                {
                    cartDetail.Amount += int.Parse(checkedSizeAmount[i]);
                    cartDetail.CartDetailTotalSum = cartDetail.Amount * product.ProductUnitPrice;
                    _cartDetailCRUD.Update(cartDetail);
                }
                else
                {
                    CartDetail newCartDetail = new CartDetail()
                    {
                        CartId = cart.CartId,
                        ProductId = product.ProductId,
                        Amount = int.Parse(checkedSizeAmount[i]),
                        CartDetailTotalSum = int.Parse(checkedSizeAmount[i]) * product.ProductUnitPrice,
                        Size = int.Parse(checkedSize[i]),
                    };

                    _cartDetailCRUD.CreateAsync(newCartDetail);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ChooseSize(string id) //This is Product's ID 
        {
            Product? product = _productCRUD.GetByIdAsync(id).Result;

            if (product == null)
            {
                return NotFound();
            }

            List<SizeDetail> sizes = _sizeDetailCRUD.GetAllByIdAsync(id).Result;

            ViewData["chosenProductSizes"] = sizes;

            return PartialView(product);
        }

        [HttpGet]
        public IActionResult Index(string categoryRadio, string priceRadio, int page = 1)
        {
            if (_productVM.products != null)
            {
                _productVM.products = _productVM.products.OrderBy(o => o.ProductName).ToList();

            }
            List<Product> productFilter = new List<Product>();
            _productVM.filters = new List<string>();
            _productVM.filters.Add(categoryRadio);
            _productVM.filters.Add(priceRadio);

            float minvalue = -1, maxvalue = -1;

            if (_productVM.products.Count > 0)
            {
                if (!string.IsNullOrEmpty(priceRadio) && !priceRadio.Equals("All"))
                {
                    string[] strsplt = priceRadio.Split('-', 2, StringSplitOptions.None);
                    minvalue = float.Parse(strsplt[0]);
                    maxvalue = float.Parse(strsplt[1]);
                }
            }

            foreach (var i in _productVM.products)
            {
                if ((i.ProductCategory.ProductCategoryName.Equals(categoryRadio)
                    || string.IsNullOrEmpty(categoryRadio)) && minCheck(minvalue, i.ProductUnitPrice)
                    && maxCheck(maxvalue, i.ProductUnitPrice))
                    productFilter.Add(i);
            }

            _productVM.products = productFilter;
            ViewBag.Product = true;
            _productVM.page = page - 1;
            ViewData["nProducts"] = _productVM.page;
            return View(_productVM);
        }

        [HttpPost]
        public IActionResult TableSort(string filter = "Name")
        {
            if (_productVM.desc)
            {
                switch (filter)
                {
                    case "Name":
                        _productVM.products = _productVM.products.OrderByDescending(i => i.ProductName).ToList();
                        break;
                    case "Price":
                        _productVM.products = _productVM.products.OrderByDescending(i => i.ProductUnitPrice).ToList();
                        break;
                    case "Color":
                        _productVM.products = _productVM.products.OrderByDescending(i => i.Color).ToList();
                        break;
                    case "Category":
                        _productVM.products = _productVM.products.OrderByDescending(i => i.ProductCategory).ToList();
                        break;
                    case "Amount":
                        _productVM.products = _productVM.products.OrderByDescending(i => i.Amount).ToList();
                        break;
                }
            }
            else
            {
                switch (filter)
                {
                    case "Name":
                        _productVM.products = _productVM.products.OrderBy(i => i.ProductName).ToList();
                        break;
                    case "Price":
                        _productVM.products = _productVM.products.OrderBy(i => i.ProductUnitPrice).ToList();
                        break;
                    case "Color":
                        _productVM.products = _productVM.products.OrderBy(i => i.Color).ToList();
                        break;
                    //case "Category":
                    //    _productVM.products = _productVM.products.OrderBy(i => i.ProductCategory).ToList();
                    //    break;
                    case "Amount":
                        _productVM.products = _productVM.products.OrderBy(i => i.Amount).ToList();
                        break;
                }
            }


            if (_productVM.desc)
                _productVM.desc = false;
            else
                _productVM.desc = true;

            return PartialView("_ViewAll", _productVM);
        }

        [HttpPost]
        public IActionResult Sort(ProductVM productVM)
        {
            List<Product> productFilter = new List<Product>();
            _productVM.filters = new List<string>();
            _productVM.filters.Add(productVM.categoryRadio);

ShoeStoreManagement/Controllers/DetailProductController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeStoreManagement.Core.Models;
using ShoeStoreManagement.Core.ViewModel;
using ShoeStoreManagement.CRUD.Implementations;
using ShoeStoreManagement.CRUD.Interfaces;
using System.Security.Claims;

namespace ShoeStoreManagement.Controllers
{
    public class DetailProductController : Controller
    {
        private readonly IProductCRUD _productCRUD;
        private readonly ICartCRUD _cartCRUD;
        private readonly ICartDetailCRUD _cartDetailCRUD;
        private readonly ISizeDetailCRUD _sizeDetailCRUD;
        private readonly IImageCRUD _imageCRUD;
        private readonly IProductCategoryCRUD _productCategoryCRUD;
        private static ProductVM _productVM = new ProductVM();

        public DetailProductController(IProductCRUD productCRUD, ISizeDetailCRUD sizeDetailCRUD, ICartCRUD cartCRUD, ICartDetailCRUD cartDetailCRUD, IImageCRUD imageCRUD, IProductCategoryCRUD productCategoryCRUD)
        {
            _productCRUD = productCRUD;
            _sizeDetailCRUD = sizeDetailCRUD;
            _cartCRUD = cartCRUD;
            _cartDetailCRUD = cartDetailCRUD;
            _imageCRUD = imageCRUD;
            _productCategoryCRUD = productCategoryCRUD;
        }

        [HttpGet]
        public IActionResult Index(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product? product = _productCRUD.GetByIdAsync(id).Result;

            if (product == null)
            {
                return NotFound();
            }

            List<SizeDetail> sizeDetails = _sizeDetailCRUD.GetAllByIdAsync(product.ProductId).Result;

            product.Sizes = sizeDetails;

            List<Image> images = _imageCRUD.GetAllByProductIdAsync(product.ProductId).Result;

            if (images != null && images.Count > 0)
            {
                product.ImageNames = new List<string>();

                foreach (var item in images)
                {
                    if (item.ImageName != product.ImageName)
                        product.ImageNames.Add(item.ImageName);
                }
            }

            ProductCategory? productCategory = _productCategoryCRUD.GetByIdAsync(product.ProductCategoryId).Result;

            if(productCategory != null)
            {
                product.ProductCategory = productCategory;
            }

            List<Product> products = _productCRUD.GetAllAsync().Result.Where(o => o.ProductCategoryId == product.ProductCategoryId).ToList();

            _productVM.productId = product.ProductId;
            _productVM.product = product;
            _productVM.products = products;

            return View(_productVM);
        }

        [HttpPost]
        public void AddToCart(int amount, int size)
        {
            _productVM.AmountSelected = amount;
            _productVM.Size = size;

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Cart? cart = _cartCRUD.GetAsync(userId).Result;

            if (cart == null)
            {
                cart = new Cart();
                cart.UserId = userId;
                _cartCRUD.CreateAsync(cart);
            }

            Product? product = _productCRUD.GetByIdAsync(_productVM.productId).Result;

            if (product == null)
            {
                return;
            }

            CartDetail? cartDetail = _cartDetailCRUD.GetByProductIdAsync(_productVM.productId, cart.CartId, _productVM.Size).Result;

            if (cartDetail != null)
            {
                if (cartDetail.Amount < product.Amount)
                {
                    cartDetail.Amount += _productVM.AmountSelected;
                    cartDetail.CartDetailTotalSum = cartDetail.Amount * product.ProductUnitPrice;
                    _cartDetailCRUD.Update(cartDetail);
                }
            }
            else
            {
                cartDetail = new CartDetail()
                {
                    CartId = cart.CartId,
                    ProductId = _productVM.productId,
                    Amount = _productVM.AmountSelected,
                    Size = _productVM.Size,
                    CartDetailTotalSum = product.ProductUnitPrice * _productVM.AmountSelected,
                };

                _cartDetailCRUD.CreateAsync(cartDetail);
            }

            if (cartDetail.IsChecked)
            {
                cart.CartTotalAmountSelected += _productVM.AmountSelected;
                cart.CartTotalPrice = cartDetail.Amount * product.ProductUnitPrice;
            }

            cart.CartTotalAmount += _productVM.AmountSelected;


            return;
        }
    }
}

ShoeStoreManagement/Views/Home/Index.cshtml
@using ShoeStoreManagement.Areas.Admin.Controllers
@using ShoeStoreManagement.Views.Shared.Components;
@using ShoeStoreManagement.Core.Models;
@using ShoeStoreManagement.Core.ViewModel;
@using Microsoft.AspNetCore.Components;
@using Microsoft.AspNetCore.Components.Web;

@model ProductVM

@{
	ViewData["Title"] = "Home Page";
	List<string> priceFilters = new List<string> { "", "0-10", "10-100", "100-1000" };
}

<div class="row">
	<form asp-action="Sort" method="post" class="borderCustom1 col-lg-3 d-lg-block collapse um" onsubmit="return jQueryAjaxSort(this);">
		<div class="form-group col">
			<div class="row">
				<ii class="row-1 h6 mb-2 mt-4">Category</ii>
				<div class="radioLayoutTabCustom row-cols-6 w-100" style="max-height:260px; overflow-y:scroll; overflow-x:hidden">
					@if (string.IsNullOrEmpty(Model.filters[0]))
					{
						<label class="radioLayoutTabCustom">
							<input type="radio" class="form-check-input" value="" name="categoryRadio" checked />
							All
						</label>

					}
					@if (!string.IsNullOrEmpty(Model.filters[0]))
					{
						<label class="radioLayoutTabCustom">
							<input type="radio" class="form-check-input p-2" value="" name="categoryRadio" />
							All
						</label>
					}
					@foreach (ProductCategory i in Model.productCategories)
					{
						if (i.ProductCategoryName.Equals(Model.filters[0]))
						{
							<label class="radioLayoutTabCustom">
								<input type="radio" value="@i.ProductCategoryName" class="form-check-input" name="categoryRadio" checked />
								@i.ProductCategoryName
							</label>
						}
						else
						{
							<label class="radioLayoutTabCustom">
								<input type="radio" value="@i.ProductCategoryName" class="form-check-input" name="categoryRadio" />
								@i.ProductCategoryName
							</label>
						}
					}
				</div>
			</div>

			<div class="row mt-4">
				<ii class="row-1 h6">Price</ii>

				<div class="radioLayoutTabCustom row-cols-6 w-100 mt-2">
					@foreach (string i in priceFilters)
					{
						if (i.Equals(Model.filters[1]))
						{
							<label class="radioLayoutTabCustom"> <input type="radio" value="@i" name="priceRadio" class="form-check-input" checked />@i</label>
						}
						else if (string.IsNullOrEmpty(i))
						{
							<label class="radioLayoutTabCustom"> <input type="radio" value="" name="priceRadio" class="form-check-input" checked />All</label>
						}
						else
						{
							<label class="radioLayoutTabCustom"> <input type="radio" value="@i" name="priceRadio" class="form-check-input" />@i</label>
						}
					}
				</div>
			</div>

			<input class="btn btn-secondary rounded w-100 mt-5" type="submit" value="Sort" />
		</div>
	</form>

	<div class="col-lg-9 col-md-12">
		<div class="d-flex d-lg-block justify-content-between">
			<button class="filter-icon border-0 d-lg-none fs-3" data-bs-toggle="collapse" data-bs-target=".um" aria-controls="navbarSupportedContent"
					aria-expanded="false" aria-label="Toggle navigation">
				<span class="h5">Filter</span>
			</button>
			<div>
				<form asp-action="Search" method="post" onsubmit="return jQueryAjaxSort(this);" class="d-flex justify-content-end mb-2 w-10">
					<input class="form-control" type="text" name="searchString" />
					<button class="btn btn-secondary icon-search" type="submit" />
				</form>
			</div>
		</div>

		<div class="row" id="hihi">
			<partial name="_ViewAll" model=@Model view-data="ViewData" />
		</div>
	</div>

</div>

ShoeStoreManagement/Views/Home/WishList.cshtml
@using ShoeStoreManagement.Views.Shared.Components;
@using ShoeStoreManagement.Core.Models;
@model WishList;

@{
    ViewData["Title"] = "WishList Page";

    List<ProductCategory> categories = ViewData["categories"] as List<ProductCategory>;
}



<div class="row">
    <div class="col-lg-3 d-lg-block collapse um">
        <div class="row">
            <ii class="row-1 h6">Category</ii>
            <div class="tabCustom row-cols-6 w-100" style="max-height:260px; overflow-y:scroll; overflow-x:hidden">
                <a class="tabCustom" style="height:50px;" asp-action="WishList" asp-route-filter="All" type="button">All</a>
                @foreach (ProductCategory i in categories)
                {
                    <a class="tabCustom" style="height:50px;" asp-action="WishList" asp-route-filter="@i.ProductCategoryName" type="button">@i.ProductCategoryName</a>
                }
            </div>
        </div>

    </div>

    <div class="col-lg-9 col-md-12 row">
        <div class="d-flex d-lg-block justify-content-end">
            <button class="filter-icon border-0 d-lg-none fs-3" data-bs-toggle="collapse" data-bs-target=".um" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="h5">Filter</span>
            </button>
        </div>
        @if (Model != null && Model.WishListDetails.Count > 0)
        {
            <div class="col-lg-4 col-sm-6 col-6">
                @foreach (var item in Model.WishListDetails)
                {
                    <component type="typeof(ProductCard)"
                       render-mode="ServerPrerendered" param-product=@item.Product param-isLiked=true param-imageName=@item.Product.ImageName />
                }
            </div>
        }
    </div>
</div>

ShoeStoreManagement/Views/Home/Wishes.cshtml
@{
    ViewData["Title"] = "Wishes Page";
}

@{
    var i = 0;
}

<section class="container-fluid mt-5">
    <div class="row gx-3 gy-4 overflow-hidden">
        @while (i < 6)
        {
            <div class="col-sm-3">
                <div class="product-card card">
                    @*<img src="" class="card-img-top" alt="">*@
                    <div class="card-img-top"></div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-start">
                            <h5 class="card-title">Product name</h5>
                            <i class="fa-regular fa-heart icon-small"></i>
                        </div>
                        <h5 class="card-title product-card-price fw-bold">20.000</h5>
                        <a href="#" class="btn btn-primary float-end mt-4">Add to Cart</a>
                    </div>
                </div>
            </div>
            i++;
        }
    </div>
    <nav aria-label="Page navigation" class="mt-5">
        <ul class="pagination pagination-lg justify-content-center">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</section>

ShoeStoreManagement/Views/Home/_ViewAll.cshtml
@using ShoeStoreManagement.Core.Models
@using ShoeStoreManagement.Core.ViewModel
@using ShoeStoreManagement.Views.Shared.Components

@model ProductVM

@{
    int nProducts = 0;
    nProducts = Model.page;

    int countPage()
    {

        int numberPages = 0;
        int numberProducts = 0;

        foreach (Product i in Model.products)
        {
            numberProducts++;
        }

        numberPages = numberProducts / 10;

        if (numberProducts % 10 != 0)
            numberPages++;

        return numberPages;
    }
}

<div>
    <div class="col row">
        @foreach (var item in Model.products)
        {
            <div class="col-lg-4 col-sm-6 col-6">
                @*<component type="typeof(ProductCard)"
            render-mode="ServerPrerendered"
            param-product=@item
            param-imageName=@item.ImageName
            param-isLiked=@item.IsLiked
            param-url1=@Url.Action("AddToWishList","Home",null,Context.Request.Scheme)
            param-url2=@Url.Action("RemoveFromWishList","Home",null,Context.Request.Scheme) />*@
                <div class="card border-0 mb-5" style="height:fit-content">

                    @if (String.IsNullOrEmpty(@item.ImageName))
                    {
                        item.ImageName = "product-empty.png";
                    }

                    <img src="image/@item.ImageName"
                     class="card-img-top img w-100 h-auto"
                     asp-append-version="true" onclick="(location.href = '@(Url.Action("Index", "DetailProduct",new { id= item.ProductId }))')" />

                    <div class="card-body">
                        <p class="fw-bold h4 text-dark mb-1 limit-line">@item.ProductName</p>
                        <div class="d-flex justify-content-between">
                            <p class="big-caption mb-2">@item.Color</p>
                            <p class="h4 mb-2 text-dark">@item.ProductUnitPrice</p>
                        </div>
                        <p class="big-caption text-primary mb-2">@item.Description</p>
                    </div>
                    @if (!@item.IsLiked)
                    {
                        <button class="btn btn-primary icon-heart" type="button" onclick="callWithId('@(Url.Action("AddToWishList", "Home"))','@item.ProductId')">Add to WishList</button>
                    }
                    else
                    {
                        <button class="btn btn-secondary icon-heart" type="button" onclick="callWithId1('@(Url.Action("RemoveFromWishList", "Home"))','@item.ProductId')">Remove from WishList</button>
                    }
                </div>
            </div>
        }
    </div>


    <nav class="container">
        <ul class="pagination" style="display:flex; flex-direction:row">
            @if (nProducts != 0)
            {
                if (nProducts > 1) nProducts -= 1;
                <li class="page-item"><button class="page-link" name="page" value=@nProducts type="submit">Previous</button></li>
            }
            @for (int i = 1; i <= @countPage(); i++)
            {
                if (i == nProducts + 1)
                {
                    <li class="page-item"><button class="page-link" name="page" value=@i type="submit" style="background-color:lightgrey" disabled>@i</button></li>
                }
                else
                {
                    <li class="page-item"><button class="page-link" type="submit" onclick="jQueryAjaxPagination('@(Url.Action("Pagination", "Product"))',@i)">@i</button></li>
                }
            }
            @if (nProducts + 1 != @countPage() && @countPage() > 0)
            {
                nProducts += 2;
                <li class="page-item"><button class="page-link" name="page" value=@nProducts type="submit">Next</button></li>
            }
        </ul>
    </nav>
</div>